Fix Mockito/Hamcrest build classpath conflict
* Fixes issue with Mockito classes not found on the vaadin-client test classpath
* Fixes Mockito/Hamcrest dependency conflict described in
       https://tedvinke.wordpress.com/2013/12/17/mixing-junit-hamcrest-and-mockito-explaining-nosuchmethoderror/

Change-Id: I946c464118e3b9365bb8da4fb337fd45e6073f5e