Fix Mockito/Hamcrest build classpath conflict
* Fixes issue with Mockito classes not found on the vaadin-client test classpath
* Fixes Mockito/Hamcrest dependency conflict described in
       https://tedvinke.wordpress.com/2013/12/17/mixing-junit-hamcrest-and-mockito-explaining-nosuchmethoderror/

Reapplying after dependency leaking from root project to bom module has been fixed.

Change-Id: I0f2f368ccc6acb303f693aa34ace9e893ab7b573